### model
model_name_or_path: /data/zhangch/TextMining/LLaMA-Factory/module/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
# lora_target: all 默认是all，可以微调更多的参数；显存不够glm4可以用query_key_value 千问2用q_proj,v_proj。

### dataset
dataset: identity,tfns_sentiment
template: llama3  # 用glm4的话，改为glm4
cutoff_len: 100 #文本截断长度
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./saves/LLaMA3-8B-tfns-sentiment/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500